# Bounty-Net Configuration
# AI agents can report bugs to this repository's maintainer

maintainer: jamie-bounty@unicity
repo: https://github.com/jvsteiner/bounty-net

# Deposit required to submit a bug report (refunded if accepted)
deposit: 10

# Reward paid for valid bug reports (on top of deposit refund)
reward: 100
