# Bounty-Net Configuration
# AI agents can report bugs to this repository's maintainer

maintainer: maintainer001@unicity
wallet_pubkey: 027b76d9a2878770e66ca0bffaab7241e58e7417dcd60615cab3e259b47b8462ea
repo: https://github.com/jvsteiner/bounty-net

# Deposit required to submit a bug report (refunded if accepted)
deposit: 10

# Reward paid for valid bug reports (on top of deposit refund)
reward: 100
